### PR TITLE
Add ignore_error option to Committee::Middleware::RequestValidation

### PR DESCRIPTION
**Pull request by kapone89**

### CODE REVIEW

**Comment by ota42y** [comment]
It should be supported on the request validation, thank you

**Comment by kapone89** [comment]
@ota42y Gr8 :+1: When we can expected the new release?

**Comment by ota42y** [comment]
Sorry for late release...
I'll release new version when I merged #249

**Comment by ota42y** [comment]
I just released 3.3.0 which include this changes 🎉 
https://rubygems.org/gems/committee/versions/3.3.0

**Comment by kapone89** [comment]
> I just released 3.3.0 which include this changes tada
> https://rubygems.org/gems/committee/versions/3.3.0

@ota42y Thank you :+1:

**Pull request merged**
