### PR TITLE
Allow rack 2

### PR DESCRIPTION
**Pull request by mtsmfm**
Rails 5 requires rack 2

### CODE REVIEW

**Comment by brandur** [comment]
Thanks!

**Comment by brandur** [comment]
Released as 1.14.0.

**Comment by dmathieu** [comment]
Should we really use a `>=`?
How about `['~> 1.5', '~> 2.0']`

**Comment by brandur** [comment]
> How about ['~> 1.5', '~> 2.0']

@dmathieu Fair point! I guess one thing to consider is whether the fairly constrained interface to Rack that's used by Committee is ever likely to really change significantly (it's definitely possible, but based on the changes required for an upgrade from v1 to v2, we may be able to forecast that it's not probably). Thoughts?

**Comment by dmathieu** [comment]
How is committee using rack?

**Comment by brandur** [comment]
I think it's basically two things:

1. The `Rack::Request` interface, i.e.

    ``` ruby
    r = Rack::Request.new(env)
    r.path_info
    ```

2. The classic Rack interface of `status, headers, lines = app.call(env)` (used implicitly as Committee is middleware).

**Comment by dmathieu** [comment]
Yeah, this changing in rack would require a lot of heads up.
Keeping the current global version should be fine.

**Comment by brandur** [comment]
Cool :)

**Pull request merged**
