### PR TITLE
add ignore_error option

### PR DESCRIPTION
**Pull request by ota42y**
ResponseValidator ignore error when this option is true.

https://github.com/interagent/committee/issues/217

### CODE REVIEW

**Comment by qsona** [comment]
Thank you! I'll try this for now, hopefully in the production env.

**Comment by knu** [comment]
It'd be great if you could access the error information, like from within a request spec.

**Comment by ota42y** [comment]
@knu 
Hi! You can use 'error_handler' option to get error information even in request specification.
(Or you have others problem?)

**Comment by ohbarye** [comment]
Hello @ota42y I'd love this `ignore_error` feature.
If you'd take any action to merge and release this feature I really appreciate you.

📝 This might be a little help for that: I've confirmed that this pull request's change correctly works by using `ignore_error` with `error_handler`, then I was able to realize what I've wanted to do on my application (As you described in https://github.com/interagent/committee/issues/217#issuecomment-478492344, just logging an error without returning a committee's custom response).

**Comment by ota42y** [comment]
Thank you your report! @ohbarye 
I'm going to merge and release this change!

**Comment by ota42y** [comment]
I just released 3.2.0!
https://rubygems.org/gems/committee/versions/3.2.0

**Comment by ohbarye** [comment]
super cool, thank you! @ota42y

**Pull request merged**
